services:
  ui:
    image: ${CI_REGISTRY_IMAGE}:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    deploy:
      mode: global
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
